use heap to ensure that miners cannot get kicked from the network by being unlucky
womboai/wombo-bittensor-subnet pull request #11
Opened 2024-02-29 20:43 UTC by amritparmanand

2024-02-29 21:15 UTC, abhinavramana commented on neuron-selector/neuron_selector/uids.py
> +import heapdict
curious: why not priorityQueue

2024-02-29 21:15 UTC, abhinavramana commented on neuron-selector/neuron_selector/uids.py
> +    )
What is the point of randomizing if you still want priority with get_n_lowest_values

2024-02-29 21:17 UTC, amritparmanand commented on neuron-selector/neuron_selector/uids.py
> +    )
it does not randomize the values in the heap, only the uid list. if it is not randomized then each new validator that starts up will have the exact same order that it will run all the miners in which would basically cause the same issue we currently have.

2024-02-29 21:20 UTC, amritparmanand commented on neuron-selector/neuron_selector/uids.py
> +import heapdict
much easier to work with. the methods given by heapdict and being able to query values like a dict without removing them is much better for this application.

2024-02-29 21:38 UTC, amritparmanand commented
ehhhh there are a lot of edge cases that I am not sure about the behavior of atm, will need to verify some details with ash before I can truly be sure this is ready

2024-03-01 01:14 UTC, MsRandom requested changes

2024-03-01 01:14 UTC, MsRandom commented on validator/validator/validator.py
> +                "miner_heap": self.miner_heap,
I don't think this works, miner_heap isn't a tensor

2024-03-01 05:34 UTC, amritparmanand commented on validator/validator/validator.py
> +                "miner_heap": self.miner_heap,
that makes sense, but step is an int and hotkeys is list[str], do those cast themselves?

2024-03-03 03:47 UTC, MsRandom commented on validator/validator/validator.py
> +                "miner_heap": self.miner_heap,
I'm not actually sure how list[str] would work. It probably uses pickle internally, so it might actually work with no changes

2024-03-04 15:56 UTC, amritparmanand commented on validator/validator/validator.py
> +                "miner_heap": self.miner_heap,
ahh ok, will remove this then

2024-03-04 22:54 UTC, amritparmanand commented on validator/validator/validator.py
> +                "miner_heap": self.miner_heap,
it indeed does work with no changes

2024-03-04 22:57 UTC, MsRandom approved these changes

2024-03-04 22:58 UTC, merged